import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-partner-revenue-share-settlement-reconciliation",
  "engine": "recovery",
  "title": "Partner Revenue-Share Settlement Reconciliation",
  "shortTitle": "Partner Revenue-Share Settlement Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through partner revenue-share settlement reconciliation",
  "industry": "Partner Revenue Operations",
  "uiPort": 4634,
  "apiPort": 5634,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Partner Revenue-Share Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidSettlement",
    "expectedKey": "expectedSettlement",
    "actualLabel": "Partner Paid Settlement",
    "expectedLabel": "Contract-Expected Settlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Partner Revenue-Share Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("partner-agreement-library","PRS01","Partner agreement library","Execute partner agreement library using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed partner agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Partner agreement library Reference","text","PRS01-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("product-channel-registry","PRS02","Product channel registry","Execute product channel registry using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed product channel registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Product channel registry Reference","text","PRS02-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("transaction-ingestion","PRS03","Transaction ingestion","Execute transaction ingestion using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Transaction ingestion Reference","text","PRS03-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("gross-revenue-reconstruction","PRS04","Gross revenue reconstruction","Execute gross revenue reconstruction using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed gross revenue reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Gross revenue reconstruction Reference","text","PRS04-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("refund-chargeback-allocation","PRS05","Refund chargeback allocation","Execute refund chargeback allocation using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed refund chargeback allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Refund chargeback allocation Reference","text","PRS05-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("tax-pass-through-exclusion","PRS06","Tax pass-through exclusion","Execute tax pass-through exclusion using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed tax pass-through exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Tax pass-through exclusion Reference","text","PRS06-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("revenue-share-tier-calculation","PRS07","Revenue-share tier calculation","Execute revenue-share tier calculation using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed revenue-share tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Revenue-share tier calculation Reference","text","PRS07-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("minimum-guarantee-tracking","PRS08","Minimum guarantee tracking","Execute minimum guarantee tracking using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed minimum guarantee tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Minimum guarantee tracking Reference","text","PRS08-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("marketing-service-fee-validation","PRS09","Marketing service fee validation","Execute marketing service fee validation using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed marketing service fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Marketing service fee validation Reference","text","PRS09-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("partner-statement-reconciliation","PRS10","Partner statement reconciliation","Execute partner statement reconciliation using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed partner statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Partner statement reconciliation Reference","text","PRS10-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("missing-payment-detection","PRS11","Missing payment detection","Execute missing payment detection using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed missing payment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Missing payment detection Reference","text","PRS11-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("settlement-generation","PRS12","Settlement generation","Execute settlement generation using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed settlement generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Settlement generation Reference","text","PRS12-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("partner-dispute-workflow","PRS13","Partner dispute workflow","Execute partner dispute workflow using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed partner dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Partner dispute workflow Reference","text","PRS13-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("cash-reconciliation","PRS14","Cash reconciliation","Execute cash reconciliation using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Cash reconciliation Reference","text","PRS14-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]}),
feature("partner-product-profitability","PRS15","Partner product profitability","Execute partner product profitability using partner agreements, products, channels, transactions, gross revenue, refunds, chargebacks, taxes, pass-throughs, revenue-share tiers, guarantees, marketing fees, statements, and cash.","Produce a governed partner product profitability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Partner / Commercial Program","text","Partner / Commercial Program · Standard Case"],["caseReference","Partner product profitability Reference","text","PRS15-2026-001"],["paidSettlement","Partner Paid Settlement","currency",1215500],["expectedSettlement","Contract-Expected Settlement","currency",1434290],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Partner agreement library case","Product channel registry case","Transaction ingestion case","Gross revenue reconstruction case","Refund chargeback allocation case"]})
]);
